# Generated by Django 4.1.6 on 2023-03-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogBauti', '0002_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'Avatares'},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='DEFAULT.png', null=True, upload_to='avatares'),
        ),
    ]
